### ISSUE TITLE
FaceSDK

### ISSUE THREAD

**Issue by Noemata** [JerryNixon/LaunchAtlanta#2]
Where would mere mortals get the FaceSDK bits that you're using here?  In particular, I've never seen Microsoft.FaceSDK.Reconstruction out in the wild.

I'd very much like to be able to use this tech!!!

**Comment by JerryNixon** [comment]
It's not out in the wide.

**Comment by Noemata** [comment]
So is this just a teaser then?  Given the sorts of things you typically post, this seems to be in a different category?  And if so, will the FaceSDK components referenced here ever be visible to the non-insider development community?
